[package]
name = "rs_lambdas"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { version = "0.15.1", default-features = false, features = ["apigw"] }
base64 = "0.22.1"
http = "1.1.0"
lambda_http = "0.13.0"
# lambda_runtime = "0.13.0"
serde_json = "1.0.128"
tokio = "1.40.0"
